/** @type {import('./$types').PageServerLoad} */
export async function load() {
  // TODO: replace with real fetch once api-gateway /leaderboard is implemented
  // const API_BASE = process.env.API_BASE_URL ?? 'http://localhost:8000';
  // const res = await fetch(`${API_BASE}/leaderboard?limit=100`);
  // if (!res.ok) throw error(500, 'Could not load leaderboard.');
  // return await res.json();

  // --- Mock data (mirrors the shape api-gateway will return) ---
  return {
    generated_at: '2026-04-19T09:00:00Z',
    snapshot_period: 'last 90 days',
    total_forecasters: 4217,
    entries: [
      {
        rank: 1,
        user: { id: 'usr_001', username: 'cassandra_t',   display_name: 'Cassandra T.' },
        brier_skill_score: 0.341,
        mean_brier_score: 0.122,
        calibration_score: 0.94,
        accuracy: 0.78,
        resolved_predictions: 412,
        platforms: ['kalshi', 'polymarket', 'manifold', 'metaculus'],
      },
      {
        rank: 2,
        user: { id: 'usr_002', username: 'delphi_oracle', display_name: 'Delphi' },
        brier_skill_score: 0.318,
        mean_brier_score: 0.131,
        calibration_score: 0.92,
        accuracy: 0.76,
        resolved_predictions: 298,
        platforms: ['polymarket', 'manifold', 'metaculus'],
      },
      {
        rank: 3,
        user: { id: 'usr_003', username: 'tiresias_ii',   display_name: 'Tiresias II' },
        brier_skill_score: 0.287,
        mean_brier_score: 0.142,
        calibration_score: 0.90,
        accuracy: 0.74,
        resolved_predictions: 523,
        platforms: ['kalshi', 'manifold'],
      },
      {
        rank: 4,
        user: { id: 'usr_abc123', username: 'jeremiah_b', display_name: 'Jeremiah B.' },
        brier_skill_score: 0.237,
        mean_brier_score: 0.162,
        calibration_score: 0.91,
        accuracy: 0.72,
        resolved_predictions: 189,
        platforms: ['kalshi', 'polymarket', 'manifold', 'metaculus'],
      },
      {
        rank: 5,
        user: { id: 'usr_005', username: 'nostradumbass', display_name: 'Nostra D.' },
        brier_skill_score: 0.221,
        mean_brier_score: 0.168,
        calibration_score: 0.88,
        accuracy: 0.71,
        resolved_predictions: 267,
        platforms: ['kalshi', 'polymarket'],
      },
      {
        rank: 6,
        user: { id: 'usr_006', username: 'bayes_is_bae',  display_name: 'bayes_is_bae' },
        brier_skill_score: 0.198,
        mean_brier_score: 0.176,
        calibration_score: 0.87,
        accuracy: 0.70,
        resolved_predictions: 155,
        platforms: ['manifold', 'metaculus'],
      },
      {
        rank: 7,
        user: { id: 'usr_007', username: 'prob_weaver',   display_name: 'Prob Weaver' },
        brier_skill_score: 0.176,
        mean_brier_score: 0.183,
        calibration_score: 0.89,
        accuracy: 0.69,
        resolved_predictions: 231,
        platforms: ['polymarket', 'manifold', 'metaculus'],
      },
      {
        rank: 8,
        user: { id: 'usr_008', username: 'kalshi_kid',    display_name: 'Kalshi Kid' },
        brier_skill_score: 0.154,
        mean_brier_score: 0.191,
        calibration_score: 0.86,
        accuracy: 0.68,
        resolved_predictions: 344,
        platforms: ['kalshi'],
      },
      {
        rank: 9,
        user: { id: 'usr_009', username: 'futarchy_fan',  display_name: 'Futarchy Fan' },
        brier_skill_score: 0.132,
        mean_brier_score: 0.198,
        calibration_score: 0.84,
        accuracy: 0.67,
        resolved_predictions: 178,
        platforms: ['manifold'],
      },
      {
        rank: 10,
        user: { id: 'usr_010', username: 'epistemic_ed',  display_name: 'Epistemic Ed' },
        brier_skill_score: 0.118,
        mean_brier_score: 0.204,
        calibration_score: 0.85,
        accuracy: 0.66,
        resolved_predictions: 289,
        platforms: ['metaculus', 'manifold'],
      },
      {
        rank: 11,
        user: { id: 'usr_011', username: 'sharpe_shooter', display_name: 'Sharpe Shooter' },
        brier_skill_score: 0.097,
        mean_brier_score: 0.212,
        calibration_score: 0.83,
        accuracy: 0.65,
        resolved_predictions: 201,
        platforms: ['kalshi', 'polymarket'],
      },
      {
        rank: 12,
        user: { id: 'usr_012', username: 'longtail_lena',  display_name: 'Longtail Lena' },
        brier_skill_score: 0.081,
        mean_brier_score: 0.219,
        calibration_score: 0.82,
        accuracy: 0.64,
        resolved_predictions: 167,
        platforms: ['metaculus'],
      },
      {
        rank: 13,
        user: { id: 'usr_013', username: 'superforecast_r', display_name: 'Super F.' },
        brier_skill_score: 0.064,
        mean_brier_score: 0.225,
        calibration_score: 0.80,
        accuracy: 0.63,
        resolved_predictions: 312,
        platforms: ['polymarket', 'manifold'],
      },
      {
        rank: 14,
        user: { id: 'usr_014', username: 'coin_flip_carl', display_name: 'Coin Flip Carl' },
        brier_skill_score: 0.023,
        mean_brier_score: 0.245,
        calibration_score: 0.76,
        accuracy: 0.58,
        resolved_predictions: 98,
        platforms: ['kalshi', 'manifold'],
      },
      {
        rank: 15,
        user: { id: 'usr_015', username: 'vibes_based',    display_name: 'Vibes Based' },
        brier_skill_score: -0.012,
        mean_brier_score: 0.254,
        calibration_score: 0.72,
        accuracy: 0.55,
        resolved_predictions: 142,
        platforms: ['polymarket'],
      },
    ],
  };
}
