#!/usr/bin/env python3
"""
Generate Kalshi auth headers for all REST test endpoints and write them to .env.

Usage:
    python gen_kalshi_auth.py

This script reads KALSHI_KEY_ID and KALSHI_PRIVATE_KEY_PATH from the environment
(or from a .env file in the parent directory), computes fresh RSA-PSS-SHA256
signatures for each endpoint in kalshi.http, and writes the results to
rest/.env — which VS Code REST Client picks up via {{$dotenv VARIABLE}}.

Run this script before each test session in VS Code REST Client, since the
signatures embed a timestamp and will expire.

Required env vars (set in ../.env or shell):
    KALSHI_KEY_ID            — Your API Key ID (UUID from kalshi.com/account/profile)
    KALSHI_PRIVATE_KEY_PATH  — Absolute path to your RSA private key PEM file
    KALSHI_API_BASE          — (optional) defaults to https://trading-api.kalshi.com/trade-api/v2
"""

import base64
import datetime
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Walk up the directory tree to find the nearest .env file
# (handles running from rest/, connector-kalshi/, or the project root)
# ---------------------------------------------------------------------------
_parent_env = None
for _candidate in [
    Path(__file__).parent / ".env",           # rest/.env
    Path(__file__).parent.parent / ".env",    # connector-kalshi/.env
    Path(__file__).parent.parent.parent.parent / ".env",  # project root .env
]:
    if _candidate.exists():
        _parent_env = _candidate
        break

if _parent_env and _parent_env.exists():
    for line in _parent_env.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, val = line.partition("=")
            os.environ.setdefault(key.strip(), val.strip())

# ---------------------------------------------------------------------------
# Imports that require the cryptography package (installed in connector_kalshi)
# ---------------------------------------------------------------------------
try:
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding
except ImportError:
    sys.exit(
        "ERROR: 'cryptography' package not found.\n"
        "Install it with:  pip install cryptography\n"
        "Or activate the connector-kalshi virtualenv first."
    )

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
KALSHI_KEY_ID = os.environ.get("KALSHI_KEY_ID", "")
KALSHI_PRIVATE_KEY_PATH = os.environ.get("KALSHI_PRIVATE_KEY_PATH", "")
KALSHI_API_BASE = os.environ.get(
    "KALSHI_API_BASE", "https://trading-api.kalshi.com/trade-api/v2"
)

# Endpoints to pre-sign  (method, path, env-var suffix)
ENDPOINTS = [
    ("GET", "/trade-api/v2/markets",              "MARKETS"),
    ("GET", "/trade-api/v2/markets/{ticker}",     "MARKET"),
    ("GET", "/trade-api/v2/portfolio/fills",      "FILLS"),
    ("GET", "/trade-api/v2/portfolio/settlements","SETTLEMENTS"),
]


def load_private_key(path: str):
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(
            f.read(), password=None, backend=default_backend()
        )


def sign(private_key, timestamp_ms: str, method: str, path: str) -> str:
    """Return base64-encoded RSA-PSS-SHA256 signature matching client.py logic."""
    path_without_query = path.split("?")[0]
    message = (timestamp_ms + method.upper() + path_without_query).encode("utf-8")
    sig = private_key.sign(
        message,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.DIGEST_LENGTH,
        ),
        hashes.SHA256(),
    )
    return base64.b64encode(sig).decode("utf-8")


def main():
    # Validate config
    if not KALSHI_KEY_ID:
        sys.exit("ERROR: KALSHI_KEY_ID is not set.")
    if not KALSHI_PRIVATE_KEY_PATH:
        sys.exit("ERROR: KALSHI_PRIVATE_KEY_PATH is not set.")
    if not Path(KALSHI_PRIVATE_KEY_PATH).exists():
        sys.exit(f"ERROR: Private key not found at: {KALSHI_PRIVATE_KEY_PATH}")

    private_key = load_private_key(KALSHI_PRIVATE_KEY_PATH)

    lines = [
        "# Auto-generated by gen_kalshi_auth.py — do not edit by hand.",
        f"# Generated at: {datetime.datetime.utcnow().isoformat()}Z",
        "",
        f"KALSHI_KEY_ID={KALSHI_KEY_ID}",
        f"KALSHI_API_BASE={KALSHI_API_BASE}",
        "",
    ]

    for method, path, suffix in ENDPOINTS:
        ts = str(int(datetime.datetime.now().timestamp() * 1000))
        sig = sign(private_key, ts, method, path)
        lines.append(f"# {method} {path}")
        lines.append(f"KALSHI_TS_{suffix}={ts}")
        lines.append(f"KALSHI_SIG_{suffix}={sig}")
        lines.append("")

    out_path = Path(__file__).parent / ".env"
    out_path.write_text("\n".join(lines))
    print(f"Auth headers written to: {out_path}")
    print(
        "\nNOTE: Signatures embed a timestamp. Re-run this script before each "
        "test session in VS Code REST Client."
    )


if __name__ == "__main__":
    main()
